StrongMind/culture

- box_of_autonomy.md
- metrics.md
change from sprint to iteration
> Edits from feedback

- devops_standards.md
Currently you cannot change plans and scaling is limited. You must delete and make a new one if if need to scale out or up past the meager limits of Consumption plans.
> No Consumption Plan for Prod Azure

- tech_sessions/pull_request_review_checklist.md
Co-authored-by: Derek Neighbors <derek.neighbors@strongmind.com>
> format headers

- .github/workflows/velocityCheckin.yml
adding in new workflows to push velocity information on merges
> DEVOPS-3138 merge for adding in velocity

- README.md
merge for adding in README.md's if missing
> DEVOPS-5443 merge for adding in README.md's if missing

- recruit/full-stack-developer.md
Added a requirement for creating a README with relevant information
> Add readme story to full-stack-developer.md

- tech_sessions/cohorts/topics/password-checker-tdd/README.md
> add shell type to code blocks

- box_of_autonomy.md
- engineering_leadership/passed_proposals/12_2022.md
- engineering_leadership/passed_proposals/readme.md
* added readme with expected format for recording passed proposals
* created file for passed proposals of December 2022
* updated box_of_autonomy.md to reflect passed proposal
> S: Added a directory for engineering leadership, and passed proposals

- engineering_leadership/passed_proposals/10_2022.md
- engineering_leadership/passed_proposals/11_2022.md
- engineering_leadership/passed_proposals/8_2022.md
- engineering_leadership/passed_proposals/9_2022.md
[QTY-1582](https://strongmind.atlassian.net/browse/QTY-1582)
As per this [proposal](https://flipswitch.slack.com/archives/C02GC9LSTFT/p1670371609804879), i'm adding all my previous passed proposals to the culture repo.
n/a
n/a
n/a
> QTY-1582: created entries for all my passed proposals

- tech_sessions/controllers.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-169)
To provide material for sessions about how to improve controllers.
Talk about smells in controllers and mechanisms by which to improve those.
> BEL-169 First version of controller patterns.

- tech_sessions/test_fixtures.md
Co-authored-by: Paul Shippy <paul.shippy@strongmind.com>
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-164)
Providing a process for moving toward spec based testing (and getting some of the benefits along the way, even if you don't get there)
Describe the different stages and the mechanisms to move between each stage of maturity.
Test it with teams and use feedback to improve it.
> Start of moving towards spec tests.

- tech_sessions/test_fixtures.md
- tech_sessions/test_fixtures_ruby_examples.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-178)
Adding ruby examples for spec based testing.
Separated them out into a different file.
Will test this with a team and ask for perfection game.
> BEL-178 ruby examples

- tech_sessions/test_fixtures_ruby_examples.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-181)
Some feedback from Steakholders tech ex.
Formatting, break out save assertions.
This was the result of feedback from the first use. Will continue to improve as we get more feedback.
> BEL-181 Break out save assertions into separate test

- tech_sessions/cohorts/sessions/2023_01_all_cohorts.md
[NW52-6291](https://strongmind.atlassian.net/browse/NW52-6291)
As an Product Engineering leader, I need to plan out which topics will be taught for upcoming cohort learning sessions so that I can provide an opportunity for professional growth within the department.
Simple markdown page in the `culture` repo containing the schedule
Feedback from peers
(see document)
[NW52-6291]: https://strongmind.atlassian.net/browse/NW52-6291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NW52-6291 create full schedule

- tech_sessions/test_fixtures_csharp_examples.md
- tech_sessions/test_fixtures_python_examples.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-182)
For teaching about test contexts in python.
Similar to what we did with ruby.
Will get feedback with first team (Steakholders).
> BEL-182 Python test examples

- tech_sessions/models.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-199)
First draft of a discussion of writing good models in MVC frameworks like Rails.
Brainstormed ideas with Mark and wrote up a draft.
n/a
n/a
> BEL-199 Basic outline of models in MVC discussion

- tech_sessions/cohorts/topics/user_stories.md
To build out a course outline and content around user stories.
Gather sources from the Internet and borrow heavily from Derek's presentation on User Stories.
View the rendered markdown in GitHub.
> Nw52 7402 apm cohort week1

- tech_sessions/openapi_clients.md
Will convert to Canvas course later.
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-984)
Course on OpenAPI for a weekly tech ex.
Build simple API, described it using OpenAPI spec, and generated clients in ruby and python. Asks the students at the end to find an API on which to generate a client and compare the generated client with the handwritten.
Ran through the exercises locally myself.
> BEL-984 Add Open API course as a single file

- engineering_leadership/passed_proposals/2023_5.md
https://flipswitch.slack.com/archives/C02GC9LSTFT/p1684433223019029
[QTY-3273](https://strongmind.atlassian.net/browse/QTY-3273)
Adds passed proposal from engineering leadership channel
n/a
n/a
n/a
[QTY-3273]: https://strongmind.atlassian.net/browse/QTY-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (S) QTY-3273: add passed proposal from engineering leadership

- devops_standards.md
- engineering_leadership/passed_proposals/2023_10.md
- gems.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1730?atlOrigin=eyJpIjoiMjk0ZDBmZTg2MmQyNGMxMjhkM2NkNjE4YTI3ZDdmM2UiLCJwIjoiaiJ9)
Create a living document of Approved, Deprecated and Obsolete gems for use in our Ruby/Rails projects.
Collected all gems currently in use. Based on the number of projects actively using them, the technology still in our stack and whether or not they passed decider in Slack.
> Bel 1730 Create a list of approved Gems

- templates/pull_request_template.md
Save time when filling out pull requests.
1. Provide a URL template for the JIRA link.
2. Use actual comments instead of () comments that have to be removed.
> Improve PR template

- tech_sessions/cohorts/sessions/2024_cohorts.md
To write down the layout for upcoming cohorts
Write down discussed topics from the leadership meeting from 08/01/2024
We have more topics than we can cover in 8 weeks, so discussion will need to take place on what we kick out/add
> Add cohort template for August-September

- tech_sessions/cohorts/sessions/2024_cohorts.md
> Fix Formatting for cohorts file

- gems.md
Add Langchain as an approved gem to create a clean, unified interface for interacting with LLM models.
Propose in Slack to add to approved gems.
[see proposal](https://flipswitch.slack.com/archives/C02GC9LSTFT/p1728497034442939)
N/A
N/A
> (S) langchainrb - Add langchainrb gem to approved gems list

- gems.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/KAPE-4775)
add metainspector to approved gems
n/a
n/a
> KAPE-4775:add metainspector to approved gems

- engineering_leadership/passed_proposals/2024_10.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
update culture repo to have latest passed proposal
https://flipswitch.slack.com/archives/C02GC9LSTFT/p1728599487990129
> (S): add passed porposal for disalbing comment checks in code climate

- templates/pull_request_template.md
Team Belding would like teams to start thinking more about the performance impact of code changes.
Ask a few questions on the PR.
> Add performance checklist to PR template

- gems.md
Add rack-timeout, to help us to diagnose slow-running services.
Per the passed proposal at https://flipswitch.slack.com/archives/C02GC9LSTFT/p1730936211283169 , add rack-timeout.
> Add rack-timeout

- gems.md
Passed proposal here: https://flipswitch.slack.com/archives/C02GC9LSTFT/p1700173452280029
Add to list.
> Add pretender to list of approved gems

- gems.md
To add two gems used by the [Code Critic](https://github.com/StrongMind/Helpers/pull/55)
Both gems are ~12 years old and are still actively maintained.
> adding clipboard and colorize to the list of approved gems

- templates/default_rails_cursor_rules.md
> Adding default cursor rules

- engineering_leadership/passed_proposals/2025_3.md
- gems.md
Keep track of and respond to recent passed proposals.
Document recent proposals.
Add RubyLLM to gems.
> Add recent passed proposals
